name: Minimal Arduino CI Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Or your preferred version

      - name: Install arduino_ci gem
        run: gem install arduino_ci
