name: Minimal Arduino CI Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Or your preferred version

      - name: Install Bundler
        run: gem install bundler

      - name: Create Gemfile
        run: |
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'arduino_ci'" >> Gemfile
        shell: bash

      - name: Verify Gemfile creation
        run: cat Gemfile

      - name: Install dependencies
        run: bundle check || bundle install
        shell: bash

      - name: Verify arduino_ci installation
        run: bundle exec arduino_ci --version
        shell: bash

      - name: Run Arduino CI tests
        run: bundle exec arduino_ci
        shell: bash
        
