name: Minimal Arduino CI Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Or your preferred version

      - name: Check connectivity to rubygems.org
        run: curl -I https://rubygems.org
        shell: bash

      - name: Install arduino_ci gem globally
        run: gem install arduino_ci

      - name: Verify arduino_ci installation
        run: arduino_ci --version

      - name: Run Arduino CI tests
        run: arduino_ci
